.TH devmon "1" "March 2013"
.SH NAME
devmon \- Automounts and unmounts optical and removable drives
.SH SYNOPSIS
.B devmon [AUTOMOUNT-OPTIONS]  # Run as daemon to automount
.B devmon [MOUNT-OPTIONS]      # Or run as client to manually un/mount
.SH DESCRIPTION
\fBdevmon\fP - Automounts and unmounts optical and removable drives
.SH USAGE
.TP
.B AUTOMOUNT-OPTIONS:  (these can be used only in daemon mode)
.B \-\-exec\-on\-device DEVICE "COMMAND"
Execute COMMAND after mounting DEVICE
.B \-\-exec-on-label "LABEL" "COMMAND"
Execute COMMAND after mounting LABEL
.B \-\-exec\-on\-video "COMMAND"
.B Execute COMMAND after video DVD mount
.B \-\-exec\-on\-audio "COMMAND"
Execute COMMAND after audio CD insertion
.B \-\-exec\-on\-disc  "COMMAND"
Execute COMMAND after data CD/DVD mount
.B \-\-exec\-on\-drive "COMMAND"
Execute COMMAND after drive mount
.B \-\-exec\-on\-unmount "COMMAND"
Execute COMMAND after unmount
.B \-\-exec\-on\-remove  "COMMAND"
Execute COMMAND after drive removal
.B Where the following in COMMAND will be replaced with:
.B     %d    mount point directory (eg /media/cd)
.B     %f    device name (eg /dev/sdd1)
.B     %l    label of mounted volume
.B  Multiple -\-exec-on-XXX options may be used to execute multiple commands.
.B  Other exec\-on\-XXX commands are ignored if exec\-on\-device or \-label executed.
.B \-\-mount-options "OPTIONS"
Default: noexec,nosuid,nodev,noatime
.B \-\-info-on-mount
Show mounted drive info in a popup dialog
.B \-\-no-mount
Don't mount anything, just exec (disables -\-exec\-on\-video)
.B \-\-no-unmount
Don't unmount all removable drives on exit
.TP
.B MOUNT-OPTIONS:  (these can be used only in client mode)
.B \-\-unmount-removable, \-r      
Sync and unmount all removable drives and show pop-up dialog (spacefm or zenity required)
.B \-\-unmount-recent, \-c
Unmount most recently mounted removable drive
.B \-\-unmount-optical, \-o
Unmount all optical drives (error pop-up only)
.B \-\-unmount-all, \-u
Same as -\-unmount-removable, -\-unmount-optical
.B \-\-unmount DIR|DEVICE
Unmount DEVICE or mount point DIR
.B \-\-eject DIR|DEVICE
Unmount and eject DEVICE or mount point DIR
.B \-\-mount-all, \-a
Mount all removable and optical drives
.B \-\-mount DEVICE
Mount DEVICE
.B \-\-mount-options, \-\-mount-fstype, \-\-eject-options "OPTIONS"
These options will be passed to mount or eject
.TP
.B \-\-ignore-device DEVICE
Ignore DEVICE (eg /dev/sdd1)
.B \-\-ignore-label "LABEL"
Ignore volume with LABEL
.B \-\-sync, \-s
Add sync mount option for ext2-4 ntfs ufs, or flush for fat & vfat (slower writing but safer)
.B \-\-internal
Also attempt to un/mount internal system drives (this is mostly a fix for esata issues)
.B \-\-no-gui, \-g
Do not show spacefm/zenity pop-up dialogs
.SH AUTHOR
This manual page was written by Mateusz Łukasik <mati75@linuxmint.pl>,
for the Debian GNU/Linux system (but may be used by others).
